### ISSUE TITLE
Why does contract deployment require OP_RETURN?

### ISSUE THREAD

**Issue by Sjors** [rgb-org/spec#66] opened 2019-01-28 14:57 UTC
The [spec says](https://github.com/rgb-org/spec/blob/master/01-rgb.md#commitment-scheme:

> Every contract MUST be deployed using the OP_RETURN scheme, independently from which commitment_scheme is set.

Why is this? Is this expected to change in a future version? This would be useful to clarify in the spec.

**Comment by dr-orlovsky** [comment] 2019-06-15 09:33
Have to note, that the actual code in pay-to-contract branch provides the functionality to deploy the contract also in P2C scheme

**Comment by dr-orlovsky** [comment] 2019-06-23 20:55
Closing since the issue is fixed with the PR #71

**Closed by dr-orlovsky** 2019-06-23 20:55 UTC
